### ISSUE TITLE
Gitsigns plugin highlights

### ISSUE THREAD

**Issue by tamton-aquib** [katawful/kat.nvim#20]
Hey itd be cool to have [gitsigns](https://github.com/lewis6991/gitsigns.nvim/) highlights in this awesome colroscheme.

**Comment by katawful** [comment]
Potentially going to wait until after #18 for exported color support, so if you want to use this when I add it you'll have to use `vim.g.kat_nvim_dontRender=true` for a startup cost

**Comment by katawful** [comment]
Please try branch 'gitsigns' and tell me what you think. Note that the requirement above must be in place unfortunately

**Comment by tamton-aquib** [comment]
![image](https://user-images.githubusercontent.com/77913442/182911367-0848d182-f1ce-478d-a1e9-7b2265f58f61.png)

Works perfectly, thank you!

**Comment by katawful** [comment]
Reopening as not merged yet
