### ISSUE TITLE
:AirlineTheme kat results in "airline: There is an error in theme kat."

### ISSUE THREAD

**Issue by eivindjahren** [katawful/kat.nvim#39]
As title says, kat.nvim tag=2.0 , airline tag=v.011, airline-themes commit=cc5d3490c8f4c87d29d97df414941a9df8ceb390

**Comment by katawful** [comment]
Does this happen with 1.0a/1.0?

**Comment by eivindjahren** [comment]
Yes, also happens with 1.0.

**Comment by katawful** [comment]
Thanks, will check it out

**Comment by katawful** [comment]
I can't replicate this on my end. Did you set `vim.g.kat_nvim_integrations`?

**Comment by eivindjahren** [comment]
No, but from what I understand from the docs, it defaults to all integrations.

**Comment by katawful** [comment]
For posterity, can you test lightline? I implemented it in the same way (kept the autoload vimscript that evals the lua functions)
