### ISSUE TITLE
Merge light and dark variants

### ISSUE THREAD

**Issue by Slotos** [katawful/kat.nvim#6]
[(N)Vim reloads colorscheme on background option change.](https://neovim.io/doc/user/options.html#'background')

> When a color scheme is loaded (the "g:colors_name" variable is set) setting 'background' will cause the color scheme to be reloaded.  If the color scheme adjusts to the value of 'background' this will work. However, if the color scheme sets 'background' itself the effect may be undone.

As such, it's sufficient to check for `vim.o.background` value, and select corresponding palette. This would allow one to select `colorscheme kat.nvim` or `colorscheme kat.nwim` and switch background when, for example, sun sets or rises.

Specifically, I believe this would be the core change in https://github.com/katawful/kat.nvim/blob/main/fnl/katdotnvim/main.fnl#L23 (first time dealing with LISP code, please be kind):

```
  (if (= vim.o.background "dark")
      (do (if (= katContrast :hard)
              (let- :g :colors_name "kat.nvim")
              (let- :g :colors_name "kat.nwim")))
      (= vim.o.background "light")
      (do (if (= katContrast :hard)
              (let- :g :colors_name "kat.lightenvim")
              (let- :g :colors_name "kat.lightenwim"))
```

**Comment by katawful** [comment]
I'll check this out, wasn't aware of this behavior

**Comment by katawful** [comment]
Please check the behavior with the branch `background-refactor`

**Comment by Slotos** [comment]
It works. There's a leftover color scheme name in the branch, but that's it.

https://user-images.githubusercontent.com/314453/150144624-45adf7fc-fa58-433d-92fa-ac206e6cd3dd.mp4

**Comment by katawful** [comment]
Will fix that then merge. Thanks!
